name: ignis_safe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  animations: ^2.0.11
  image_picker: ^1.2.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/avatar.png
    - assets/google.jpg
    - assets/fire_onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png
    - assets/electrical.png
    - assets/fire_ex.png
    - assets/kitchen.png
    - assets/bg.png
    - assets/module1_fire.png
    - assets/m1_fire.png
    - assets/pass.png
    - assets/class_a.png
    - assets/class_b.png
    - assets/class_c.png
    - assets/class_d.png
    - assets/class_k.png
    - assets/dev_rave.png
    - assets/dev_fatima1.jpg
    - assets/dev_sarah.jpg
    - assets/dev_andrei.jpg
    - assets/house.jpg
    - assets/condo.jpg
    - assets/prevent_kitchen.png
    - assets/response_kitchen.png
    - assets/prevent_tenement.png
    - assets/response_tenement.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: false
  web: false

  android_12:
    color: "#FFFFFF"
    image: assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21