org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
unity.androidSdkPath=C:\\Users\\Andrei\\AppData\\Local\\Android\\sdk
unity.androidNdkPath=C:\\Users\\Andrei\\AppData\\Local\\Android\\sdk\\ndk\\27.2.12479018
