org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
unity.androidSdkPath=C:\\Users\\Andrei\\AppData\\Local\\Android\\sdk
unity.androidNdkPath=C:\\Program Files\\Unity\\Hub\\Editor\\6000.4.1f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK
